// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package comment

import (
	"github.com/google/wire"
	"webooktrial/comment/grpc"
	"webooktrial/comment/ioc"
	"webooktrial/comment/repository"
	"webooktrial/comment/repository/dao"
	"webooktrial/comment/service"
	"webooktrial/pkg/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	db := ioc.InitDB()
	commentDAO := dao.NewGORMCommentDAO(db)
	loggerV1 := ioc.InitLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, loggerV1)
	commentService := service.NewCommentService(commentRepository)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	server := ioc.InitGRPCxServer(commentServiceServer, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMCommentDAO, repository.NewCommentRepo, service.NewCommentService, grpc.NewCommentServiceServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB)
