apiVersion: v1
# 这个指的是 我 k8s 有哪些 volume
#  我 k8s 有什么？？？？
kind: PersistentVolume
metadata:
  name: webooktrial-mysql-pv
spec:
  storageClassName: trial
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webooktrialdata"
