// Code generated by MockGen. DO NOT EDIT.
// Source: E:\webooktrial\internal\web\types.go

// Package jwtmocks is a generated GoMock package.
package jwtmocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *Mockhandler) RegisterRoutes(server *gin.Engine) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", server)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockhandlerMockRecorder) RegisterRoutes(server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*Mockhandler)(nil).RegisterRoutes), server)
}
